name: alfred CI

on: [push]

jobs:
  build:
    name: Publish and Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - name: Install gems
        run: |
          gem install brakeman
          gem install rubycritic
      - name: generate brakeman report
        run: brakeman > brakeman_dist || exit 0
      - name: generate rubycritic report
        run: rubycritic -p rubycritic_dist || exit 0
      - name: Upload Brakeman report
        uses: actions/upload-artifact@v2
        with:
          name: brakeman_report
          path: brakeman_dist
      - name: Upload Rubycritic report
        uses: actions/upload-artifact@v2
        with:
          name: rubycritic_report
          path: rubycritic_dist
  download_inspection_report:
    name: Brakeman results
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - name: Download Brakeman report
        uses: actions/download-artifact@v2
        with:
          name: brakeman_report
          retention-days: 3
      - name: Print the final result
        shell: bash
        run: |
          value=`cat brakeman_dist`
          echo The result is $value    
      - name: Download Rubycritic report
        uses: actions/download-artifact@v2
        with:
          name: rubycritic_report
          retention-days: 3