name: CICD

on:
  push:
    branches: [ master ]

jobs:
  pre-inspection:
    name: Publish and inspect
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Brakeman
      uses: devmasx/brakeman-linter-action@v1.0.0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}