name: alfred CI

on: [push]

jobs:
  build:
    name: Generate Reports
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - name: Install gems
        run: |
          gem install brakeman
          gem install rubycritic
      - name: Generate Brakeman Report
        run: brakeman > brakeman_dist || exit 0
      - name: Generate Rubycritic Report
        run: rubycritic -p rubycritic_dist || exit 0
      - name: Upload Brakeman Archive
        uses: actions/upload-artifact@v2
        with:
          name: brakeman_report
          path: ./brakeman_dist
          retention-days: 3
      - name: Upload Rubycritic Archive
        uses: actions/upload-artifact@v2
        with:
          name: rubycritic_report
          path: ./rubycritic_dist
          retention-days: 3
  download_inspection_report:
    name: Download Archives
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - name: Brakeman Archive
        uses: actions/download-artifact@v2
        with:
          name: brakeman_report
      - name: Print the Brakeman result
        shell: bash
        run: |
          value=`cat brakeman_dist`
          echo The result is $value    
      - name: Rubycritic Archive
        uses: actions/download-artifact@v2
        with:
          name: rubycritic_report