name: CICD

on:
  push:
    branches: [ master ]

jobs:
  pre-inspection:
    name: Publish and inspect Brakeman
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install gems
      run: |
        gem install brakeman
    - uses: actions/download-artifact@v2
      id: download
      with:
        name: 'brakeman-artifact'
        path: 'tmp/brakeman-artifact-dist'
    - name: brakeman report
      run: |
        mkdir tmp/
        brakeman -f json > tmp/${{steps.download.outputs.download-path}} || exit 0
    - name: Brakeman
      uses: devmasx/brakeman-linter-action@v1.0.0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        REPORT_PATH: tmp/brakeman.json




